// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6FZxGYenoIiIkA-Uw_xrC9XY-RnG2fGg',
    appId: '1:772631286069:web:eba406b55f0219da51fc7c',
    messagingSenderId: '772631286069',
    projectId: 'breast-cancer-5ccc7',
    authDomain: 'breast-cancer-5ccc7.firebaseapp.com',
    storageBucket: 'breast-cancer-5ccc7.appspot.com',
    measurementId: 'G-BV0LRVN11R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHfH6dHHaH86yY7W5M87j-QyEU1eflZLQ',
    appId: '1:772631286069:android:afa301629dadac9f51fc7c',
    messagingSenderId: '772631286069',
    projectId: 'breast-cancer-5ccc7',
    storageBucket: 'breast-cancer-5ccc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKSEkIQK2GYlQUMZZ8CORCTpCnc-FfxNE',
    appId: '1:772631286069:ios:ac54fae272f6ec5051fc7c',
    messagingSenderId: '772631286069',
    projectId: 'breast-cancer-5ccc7',
    storageBucket: 'breast-cancer-5ccc7.appspot.com',
    iosBundleId: 'com.example.breastcancerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKSEkIQK2GYlQUMZZ8CORCTpCnc-FfxNE',
    appId: '1:772631286069:ios:efe96cd3c4695d6451fc7c',
    messagingSenderId: '772631286069',
    projectId: 'breast-cancer-5ccc7',
    storageBucket: 'breast-cancer-5ccc7.appspot.com',
    iosBundleId: 'com.example.breastcancerapp.RunnerTests',
  );
}
